### ISSUE TITLE
查看冻结的华为智慧助手•今天 详情信息 闪退

### ISSUE THREAD

**Issue by Jesse205** [LibChecker/LibChecker#1033]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

无法查看华为智慧助手•今天的详情，点进去会闪退

### Expected behavior / 预期行为

不会闪退

### Actual behavior / 实际行为

闪退

### Steps to reproduce / 复现步骤

1. 购买 HONOR 9X
2. 升级系统至鸿蒙3
3. 冻结华为智慧助手•今天
4. 下载并安装并打开LibChecker，找到这个APP，点进去

### UI / OS

HarmonyOS

### Android Version / Android 版本

10

### Additional info / 额外信息

```
FATAL EXCEPTION: main
Process: com.absinthe.libchecker, PID: 31201
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:5121)
	at android.view.ViewGroup.addView(ViewGroup.java:5103)
	at androidx.activity.j.run(SourceFile:392)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at i3.a.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

Uploading SVID_20231203_214832_1.mp4…

**Comment by Jesse205** [comment]
https://github.com/LibChecker/LibChecker/assets/51242302/04d8e297-0946-4f93-b243-260b26c68414

**Comment by qhy040404** [comment]
看起来是这个app没有任何的feature
抽象
