### ISSUE TITLE
[BUG] 应用页面搜索框输入 dial 闪退

### ISSUE THREAD

**Issue by lc0a** [LibChecker/LibChecker#608]
### LibChecker version / LibChecker 版本

2.3.7.5f8877dc(1532)

### Bug description / Bug 描述

应用页面搜索框输入 dial 闪退。

### Expected behavior / 预期行为

出现和“dial”有关的搜索结果，且软件运行正常。

### Actual behavior / 实际行为

在应用页面搜索框输入`dial`，当输到`l`时，软件闪退。

### Steps to reproduce / 复现步骤

1.打开LibChecker，点击右上角汉堡图标（三条横线）；
2.勾选“显示系统应用” （若已勾选则无需再操作）；
3.返回，点击搜索图标，在搜索框中依次输入 `d i a l`。

### UI / OS

AOSP (Android Emulator)

### Android Version / Android 版本

11

### Additional info / 额外信息

完整的logcat文件：
[logcat.txt](https://github.com/LibChecker/LibChecker/files/10878845/logcat.txt)

以下是可能和这个bug有关的logcat片段：（位于logcat.txt的12052行至12077行）
```
03-03 14:01:31.746  2060  2060 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-03 14:01:31.746  2060  2060 E AndroidRuntime: FATAL EXCEPTION: main
03-03 14:01:31.746  2060  2060 E AndroidRuntime: Process: com.absinthe.libchecker, PID: 2060
03-03 14:01:31.746  2060  2060 E AndroidRuntime: java.lang.IllegalArgumentException: Called attach on a child which is not detached: BaseViewHolder{81eb0a8 position=3 id=3, oldPos=-1, pLpos:-1} rikka.widget.borderview.BorderRecyclerView{8d497c1 VFED..... ......ID 0,0-1080,2160 #102000a android:id/list}, adapter:com.absinthe.libchecker.r5@9079b66, layout:androidx.recyclerview.widget.LinearLayoutManager@7a6ea7, context:com.absinthe.libchecker.ui.main.MainActivity@8263447
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.b.b(SourceFile:76)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.h(SourceFile:35)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$d.b(SourceFile:8)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:630)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.o(SourceFile:152)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$a.run(SourceFile:30)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at com.absinthe.libchecker.p60.run(SourceFile:1)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-03 14:01:31.746  2060  2060 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

此外，这个bug在 #601 中也被提及。

如果取消勾选“显示系统应用”，则无论在搜索框中输入`pic`，`libc`还是`dial`，均不会闪退。

**Comment by qhy040404** [comment]
CI版本已修复
